[package]
name = "call_api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
tokio = { version = "1.40.0", features = ["full"] }